### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by knorrre** [darkbox/TimesApp#2]
Hi there,

thanks for your app!
At first I got error 500. After changing chmod to 777 all files it works. But which files have to be 777 and which can have lower rights?

Regards

**Comment by darkbox** [comment]
Hi, this was a project for my degree and actually I do not remember which files can have lower permissions that part we didn't documented at the end. But I think they must have the same permission reflected on the official documentation of CakePHP's project site.

Sorry for not be more useful.

Best regards,
Rafa

**Comment by knorrre** [comment]
# chmod -R 777 /app/tmp
That's it.
